server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 100
    accept-count: 1000
    max-connections: 10000

# spring配置
spring:
  application:
    name: spring-boot-plus
  # 当前项目maven激活环境，例如：dev/test/prod，对应pom.xml中profile设置值
  profiles:
    active: @profileActive@
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    cachePrepStmts: true
    prepStmtCacheSize: 20
    prepStmtCacheSqlLimit: 1024
    useServerPrepStmts: true
    useLocalSessionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 60000
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池最大阻塞等待时间
        max-wait: 10s
        # 连接池中的最小空闲连接
        min-idle: 10
      shutdown-timeout: 3s

# mybatis-plus配置
mybatis-plus:
  # 启动时是否检查MyBatis XML文件是否存在
  check-config-location: true
  # MyBatis原生配置
  configuration:
    # 字段名称下划线转驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: ASSIGN_ID
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  # mapper xml映射路径
  mapper-locations: classpath*:mapper/**/*Mapper.xml

# 分页
pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: count=countSql

# spring-boot-plus框架配置
spring-boot-plus:
  # swagger配置
  openapi:
    title: spring-boot-plus API Docs
    description: spring-boot-plus后台接口文档
    terms-of-service: https://github.com/geekidea
    contact-name: geekidea
    contact-url: https://geekidea.io
    contact-email: geekidea@qq.com
    version: @project.version@
    external-description: spring-boot-plus
    external-url: https://springboot.plus
  # 登录权限配置
  login:
    # 是否启用登录权限校验
    enable: true
    # 是否单次登录
    single-login: false
    # token过期时间，单位为分钟
    token-expire-minutes: 60
    # 是否校验目标方法权限
    login-permission: false
    # 排除路径
    exclude-paths:
      - /v3/api-docs/**
      - /swagger-resources/**,/swagger-ui/**,/doc.html
      - /webjars/**
      - /favicon.ico
      - /login
      - /index.html
      - /file/**
  # 日志AOP配置
  log-aop:
    # 是否启用
    enable: true
    # 是否打印日志
    print-log: true
    # 是否打印请求头
    print-head-log: false
    # 登录页面路径
    login-url: /login
    # 排除路径
    excludePaths:
      - /sysLog/**
  # XSS
  xss:
    # 是否启用，默认禁用
    enable: false
    # 拦截的路径
    url-patterns: /*
    # 排序
    order: 2
    # 是否支持异步
    async: true


# swagger配置
springdoc:
  swagger-ui:
    enabled: true


knife4j:
  enable: true
  # 启用账号密码登录
  basic:
    enable: false
    username: admin
    password: 123456
  setting:
    # 自定义底部
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: MIT License | Copyright © 2019-2023 [geekidea](https://geekidea.io)

