server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 100
    accept-count: 1000
    max-connections: 10000

spring:
  application:
    name: spring-boot-plus
  # 当前项目maven激活环境，例如：dev/test/prod，对应pom.xml中profile设置值
  profiles:
    active: dev
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    cachePrepStmts: true
    prepStmtCacheSize: 20
    prepStmtCacheSqlLimit: 1024
    useServerPrepStmts: true
    useLocalSessionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 10000
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池最大阻塞等待时间
        max-wait: 10s
        # 连接池中的最小空闲连接
        min-idle: 10
      shutdown-timeout: 3s

# logback.xml中有详细的日志配置
#logging:
#  config: classpath:logback.xml
logging:
  level:
    root: info

mybatis-plus:
  # 启动时是否检查MyBatis XML文件是否存在
  check-config-location: true
  # MyBatis原生配置
  configuration:
    # 字段名称下划线转驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: ASSIGN_ID
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  # mapper xml映射路径
  mapper-locations: classpath*:mapper/**/*Mapper.xml

# 分页
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# spring-boot-plus框架配置
spring-boot-plus:
  openapi:
    title: Spring-Boot-Plus
    description: Spring-Boot-Plus API Docs
    terms-of-service: https://github.com/geekidea
    contact-name: geekidea
    contact-url: https://geekidea.io
    contact-email: geekidea@qq.com
    version: 2.7.10-SNAPSHOT
    external-description: spring-boot-plus
    external-url: https://springboot.plus

  # 登录权限配置
  login:
    # 是否启用登录权限校验
    enable: false
    # 是否单次登录
    single-login: true
    # token过期时间，单位为分钟
    token-expire-minutes: 60
    # 是否校验目标方法权限
    login-permission: false
    # 排除路径
    exclude-paths:
      - /v3/api-docs/**
      - /swagger-resources/**,/swagger-ui/**,/doc.html
      - /login
      - /index.html
      - /file/**
      - /upload/**

  # 日志AOP配置
  log-aop:
    # 是否启用
    enable: true
    # 是否打印日志
    print-log: true
    # 是否打印请求头
    print-head-log: false
    # 登录页面路径
    login-url: /login




# swagger配置
springdoc:
  swagger-ui:
    enabled: true


#knife4j:
#  enable: true
#  openapi:
#    title: Knife4j官方文档
#    description: "`我是测试`,**你知道吗**
#    # aaa"
#    email: xiaoymin@foxmail.com
#    concat: 八一菜刀
#    url: https://docs.xiaominfo.com
#    version: v4.0
#    license: Apache 2.0
#    license-url: https://stackoverflow.com/
#    terms-of-service-url: https://stackoverflow.com/
#    group:
#      test1:
#        group-name: 分组名称
#        api-rule: package
#        api-rule-resources:
#          - com.knife4j.demo.new3

