spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_plus?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0

# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 文件上传相关配置
file:
  # 文件服务类型 本地还是OSS
  file-server-type: OSS
  oss:
    accessKeyId:
    accessKeySecret:
    endpoint:
    bucketName:
    rootDir:
    accessDomain:

# 日志配置，logback-spring.xml中会引用以下变量
logback-spring:
  # 日志文件目录
  path: logs

# 微信小程序配置
wx:
  mp:
    # AppID(小程序ID)
    appid:
    # AppSecret(小程序密钥)
    secret:


